import { app, BrowserWindow } from 'electron';
import ZealPipeReader from './zeal/zeal-pipe-reader';
import { updateElectronApp } from 'update-electron-app';
import { configStore } from './store';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

class ManaTicker {
  private manaTickWindow: BrowserWindow;
  private config = configStore.load();
  constructor() {
    this.createManaTickWindow();
    new ZealPipeReader([this.manaTickWindow]);
  }

  createManaTickWindow() {
    this.manaTickWindow = new BrowserWindow({
      width: this.config.manaTicker.width,
      height: this.config.manaTicker.height,
      x: this.config.manaTicker.x || undefined,
      y: this.config.manaTicker.y || undefined,
      frame: false,
      transparent: true,
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      },
      autoHideMenuBar: true,
      titleBarStyle: 'hidden',
    });
    this.manaTickWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
    this.manaTickWindow.setAlwaysOnTop(true, 'screen-saver');

    // Open the DevTools.
    // this.manaTickWindow.webContents.openDevTools();
    // this.manaTickWindow.setSize(800, 800);

    // Listeners
    this.manaTickWindow.on('move', () => {
      const [x, y] = this.manaTickWindow.getPosition();
      this.config.manaTicker.x = x;
      this.config.manaTicker.y = y;
      configStore.save(this.config);
    });
    this.manaTickWindow.on('resize', () => {
      const [width, height] = this.manaTickWindow.getSize();
      this.config.manaTicker.width = width;
      this.config.manaTicker.height = height;
      configStore.save(this.config);
    });
  }
}

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

app.on('ready', () => new ManaTicker());

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    new ManaTicker();
  }
});

// Update the app, but don't pop up a notification to restart, I'm not trying to get anyone killed
updateElectronApp({ notifyUser: false });
